### ISSUE TITLE
Een `detail` pagina maken waarbij je de specifieke artikelen kan lezen

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/pleasurable-ui#12]
# Schetsen
Wij hebben hiervoor schetsen gemaakt waaruit inspiratie kan worden gehaald. #6 kan je alle schetsen terugvinden.

![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009778/b67fbd06-322b-43c8-95c9-c264a7b50558)

# Wat is er allemaal nodig?
* Post interactie (die staat er al, alleen stijlen.) Deze wordt veranderd naar een share interactie ipv een like interactie. 
* Auteur moet goed naar voren komen. 
  * Kijk of je de foto naar voren kan halen
  * En het stukje waarover er meer informatie naar voren komt over deze persoon

**Comment by SamaraFellaDina** [comment]
Wat werkt beter?


![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009778/b6c78001-ae41-4071-a15b-a960024f3ae8)




![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009778/1652cbcd-1571-4b3c-bce8-e6115aeb0fe5)


Leg even uit @zainablfz welke beter werkt en waarom

**Comment by zainablfz** [comment]
Ik heb vandaag aan de detailpagina gewerkt voor mobiele versie en heb hierbij de content van het artikel een styling gegeven. 

Ik heb een lijst gemaakt van wat er nog moet gebeuren, hier ga ik morgen aan werken:

- [x] Pagina responsive maken (tablet & desktop)
- [ ] Responsive images toepassen (loading state)
- [x] Share button stylen (UI-states) & enhancen dmv client-side JS
- [x] Paar kleine dingen in de content wat beter stylen

De pagina ziet er momenteel zo uit, laat mij vooral weten wat je ervan vindt en of je feedbackpunten hebt over design/code!: 

![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009548/404ccf1f-5544-43b6-ac72-262ca1d63729)

**Comment by SamaraFellaDina** [comment]
Mobiele versie ziet er goed uit! Ik zie alleen dat alle knoppen de uiting veranderd. Klopt het dat je de main button content heb veranderd?

https://github.com/SamaraFellaDina/pleasurable-ui/blob/d3f00c07fcc35b617f9dfb9edbc9cc0c59e18d19/public/style.css#L95-L103

Want dit word nu bij elke knop toegepast. Daarnaast zal ik goed kijken of deze knop goed past bij de huisstijl van Red Pers. Ik weet niet of je het verder gaat stijlen maar als je het op een specifieke knop wilt toepassen doe het dan via een class. Maar laat maar weten :)

**Comment by SamaraFellaDina** [comment]
Het artikel ziet er verder rest top uit!!

![](https://media.giphy.com/media/tHIRLHtNwxpjIFqPdV/giphy.gif?cid=790b7611g4ytxw6grzxxxg07s30up040ge4520njtj7n1l57&ep=v1_gifs_trending&rid=giphy.gif&ct=g)
