### ISSUE TITLE
share interactie

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/pleasurable-ui#14]
Er staat al een like interactie. Je moet hiervoor de button aanpassen dat je een link krijgt om te delen

**Comment by SamaraFellaDina** [comment]
```js
app.post("/like", async function (request, response) {
    const initiatiefId = request.body.initiatiefId;
    const likes = request.body.likes;


    console.log("Like verzoek voor service met ID:", initiatiefId);
    console.log("Total likes:", likes);
    
    if (initiatiefId) {
        // Update het aantal likes in de Directus API


        fetchJson(`${apiUrl}/${initiatiefId}`, {
            method: "PATCH",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ likes: likes })
        }).then((data) => {
            console.log(data);
            console.log("Aantal likes bijgewerkt voor service:", initiatiefId, likes);
        }).catch((error) => {
            console.error("Error patching likes in Directus API:", error);
        });


    
    } else {
      // Laat het weten als de service niet gevonden is.
      console.log("Service niet gevonden voor ID:", initiatiefId);
      response.status(404).send("Service niet gevonden");
    }
  });
```
Zie [hier](https://github.com/Ryank2004/user-experience-enhanced-website/blob/main/server.js#L50-L79) Ryan zijn code

**Comment by zainablfz** [comment]
Ik heb vandaag gewerkt aan de styling van de post-button met CSS. Daarnaast heb ik het pleasurable gemaakt met een 'confetti 🎉' animatie met JS en heb ik een client-side fetch toegevoegd zodat de pagina niet herladen hoeft te worden zodat de gebruiker gelijk feedback krijgt wanneer er op de share button geklikt wordt, doordat de counter omhoog gaat zonder dat de pagina herladen hoeft te worden. Het ziet er momenteel zo uit (het lukt mij nu niet om een schermopname toe te voegen):


![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009548/a479d5d1-b60f-4c24-9c7e-0c5416d87474)


![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009548/f3a9bd94-c877-4cc6-995c-1ccc9a8fce7e)


![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009548/1544ef80-475f-48d7-ae4a-e2893474a98c)
