### ISSUE TITLE
Figma schetsen maken

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/pleasurable-ui#6]
Wij willen graag allebei een figma design maken en daarnaast kijken naar elkaars ontwerp

**Comment by SamaraFellaDina** [comment]
# Schetsen voor detailpagina `/artikel/:slug`
hee! Ik heb nu deze schets gemaakt van de detailpagina



![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009778/5dd78e87-8016-4579-807b-b76ba31d68f6)

**Comment by SamaraFellaDina** [comment]
# Schetsen voor de landingspagina `'/'`
hee! Ik heb er vandaag meer gemaakt :) Kijken we er morgen naar <3 



![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009778/e74707e4-5ccc-479c-9530-f5d2124d5710)
![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009778/5f0c0df3-0e55-42d7-9abf-83f41e2ad13e)

**Comment by zainablfz** [comment]
Hee, ik heb net de figma schetsen van de landings pagina gemaakt! 

Het is mij niet gelukt om de articles in de section met de rode background erin te krijgen, dus die heb ik even leeg gelaten. 

![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009548/84dfb0d1-5c51-4a3e-bb35-e3ed62c951f9)
![Image](https://github.com/SamaraFellaDina/pleasurable-ui/assets/144009548/0a3508e0-9637-4351-8da9-a6ae0205b286)

**Comment by SamaraFellaDina** [comment]
> Hee, ik heb net de figma schetsen van de landings pagina gemaakt!
> 
> Het is mij niet gelukt om de articles in de section met de rode background erin te krijgen, dus die heb ik even leeg gelaten.
> 
> ![Image](https://private-user-images.githubusercontent.com/144009548/330534953-84dfb0d1-5c51-4a3e-bb35-e3ed62c951f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTg4NTQsIm5iZiI6MTcxNTc1ODU1NCwicGF0aCI6Ii8xNDQwMDk1NDgvMzMwNTM0OTUzLTg0ZGZiMGQxLTVjNTEtNGEzZS1iYjM1LWUzZWQ2MmM5NTFmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwNzM1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTExZmU4ZjMwMWMzZDI1ZjNhMjBiNmI1MTJlNjk1YTU0NWRlNjQ0N2MzY2ViOTIwYzkyZmY4Mzk3NTZmNzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2usKftnNMJbgUjbTo2yH-CI47dj-WxjQXRvGXeTWXTg) ![Image](https://private-user-images.githubusercontent.com/144009548/330534952-0a3508e0-9637-4351-8da9-a6ae0205b286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTg4NTQsIm5iZiI6MTcxNTc1ODU1NCwicGF0aCI6Ii8xNDQwMDk1NDgvMzMwNTM0OTUyLTBhMzUwOGUwLTk2MzctNDM1MS04ZGE5LWE2YWUwMjA1YjI4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwNzM1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWVjOTkzZTc2YzhhNWZjY2EzOGVkNGRkM2NiMTE1MzgwMjU2NjQwYjJkZGE1N2U4OWI2N2JmM2ZkMTU4NDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gEjh5NBh-bNvgRA5FOxeCY4UZ_Rg0aI2fjuL5UurBvM)

Hee! Misschien een leuk idee om ee `onerror` te maken, waarbij als een foto nog niet geladen is hij een vervangende foto ervoor heeft. Of we moeten een blur maken voordat de foto is ingeladen.
